file(GLOB PY_FILES "${SOURCE_DIR}/*.py")
set(HEADER_CONTENT "#pragma once\n")
foreach(PY_FILE ${PY_FILES})
  get_filename_component(PY_NAME ${PY_FILE} NAME_WE)
  string(TOUPPER ${PY_NAME} PY_NAME)
  set(VAR_NAME "${PY_NAME}_PY_SCRIPT")
  file(READ ${PY_FILE} PY_CONTENT)
  string(APPEND HEADER_CONTENT "\ninline constexpr const char ${VAR_NAME}[] = R\"py_embed(\n${PY_CONTENT})py_embed\";\n")
endforeach()
file(WRITE "${OUTPUT_PATH}" "${HEADER_CONTENT}")
